on: [push, pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
    - name: checkout files in repo
      uses: actions/checkout@master
    - name: Check broken links
      uses: JohanWork/url-test-github-action@v1.0.1
      with:
        file-types: '.md'
